### PR TITLE
Adding mono support

### PR DESCRIPTION
**Pull request by simonhdickson**
I changed the tests to be **/** instead of **\\\\** which seems to work on both Mac and Windows, I don't know if there is a better way of doing this at compile time?

### CODE REVIEW

**Comment by simonhdickson** [comment]
Actually don't merge this yet, I actually forgot a commit

**Comment by pezipink** [comment]
is this ready now then? does it work? :)

**Comment by pezipink** [comment]
and yes we could have the tests themselves use the mixin tp to work out if we should use // or \\ but perhaps that would be going TOO far! lol

**Comment by simonhdickson** [comment]
Ha, yeah perhaps that might be going too far!

Yeah it does work now,

**Comment by pezipink** [comment]
Awesome! great work Simon, next stop, the world!

**Pull request merged**
